#!/usr/bin/env bash
# This script displays information about subdomains

get_subdomain_info() {
  local domain="$1"
  local subdomain="$2"

  local record_types=("www" "lb-01" "web-01" "web-02")

  if [[ -n $subdomain ]]; then
    record_types=("$subdomain")
  fi

  for record_type in "${record_types[@]}"; do
    local destination=$(dig +short "$record_type.$domain" | awk 'NR==1{print}')
    if [[ -n $destination ]]; then
      local record_type_output=$(dig +short -t "$record_type" "$record_type.$domain" | awk 'NR==1{print}')
      echo "The subdomain $record_type is a $record_type_output record and points to $destination"
    fi
  done
}

get_subdomain_info "$@"
