#!/usr/bin/env bash
# Configure HAProxy to redirect HTTP to HTTPS

# Install HAProxy if not installed
apt-get update
apt-get install -y haproxy

# Configure HAProxy to redirect HTTP to HTTPS
cat > /etc/haproxy/haproxy.cfg << EOF
frontend http_front
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }

frontend https_front
    bind *:443 ssl crt /etc/ssl/certs/haproxy.pem
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 10.0.0.1:80 check
    server web-02 10.0.0.2:80 check

EOF

# Restart HAProxy
service haproxy restart
