#!/usr/bin/env bash
# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/^\(listen .*\)80;/\180;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo /etc/init.d/nginx restart

# Create a custom HTML page
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
