#!/usr/bin/env bash
# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/^\(listen .*\)80;/\180;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Create a custom HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

