#!/usr/bin/env bash
# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx
cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        echo "Hello World!";
    }
}
EOF

# Restart Nginx
service nginx restart
